version: '2.1'
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
    volumes:
      - mysql-data:/var/lib/mysql

  wordpress:
    image: wordpress:4.8.2-apache
    links:
      - mysql:mysql
    environment:
      - VIRTUAL_HOST=localhost
      - WORDPRESS_DB_PASSWORD=wordpress
    volumes:
      - wordpress-data:/var/www/html

  proxy:
    image: jwilder/nginx-proxy
    links:
      - wordpress:wordpress
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80


volumes:
  mysql-data:
    driver: local
  wordpress-data:
    driver: local
